/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-06-30 15:48:57 UTC)
 * on 2014-07-12 at 22:33:30 UTC 
 * Modify at your own risk.
 */

package com.appspot.myapp.greetings;

/**
 * Service definition for Greetings (v1).
 *
 * <p>
 * A simple and polite API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link GreetingsRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Greetings extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the greetings library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "greetings/v1/hello/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Greetings(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Greetings(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the GreetingsAPI collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code Greetings greetings = new Greetings(...);}
   *   {@code Greetings.GreetingsAPI.List request = greetings.greetingsAPI().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public GreetingsAPI greetingsAPI() {
    return new GreetingsAPI();
  }

  /**
   * The "greetingsAPI" collection of methods.
   */
  public class GreetingsAPI {

    /**
     * Create a request for the method "greetingsAPI.hello".
     *
     * This request holds the parameters needed by the greetings server.  After setting any optional
     * parameters, call the {@link Hello#execute()} method to invoke the remote operation.
     *
     * @param who
     * @return the request
     */
    public Hello hello(java.lang.String who) throws java.io.IOException {
      Hello result = new Hello(who);
      initialize(result);
      return result;
    }

    public class Hello extends GreetingsRequest<com.appspot.myapp.greetings.model.Greeting> {

      private static final String REST_PATH = "{who}";

      /**
       * Create a request for the method "greetingsAPI.hello".
       *
       * This request holds the parameters needed by the the greetings server.  After setting any
       * optional parameters, call the {@link Hello#execute()} method to invoke the remote operation.
       * <p> {@link
       * Hello#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param who
       * @since 1.13
       */
      protected Hello(java.lang.String who) {
        super(Greetings.this, "POST", REST_PATH, null, com.appspot.myapp.greetings.model.Greeting.class);
        this.who = com.google.api.client.util.Preconditions.checkNotNull(who, "Required parameter who must be specified.");
      }

      @Override
      public Hello setAlt(java.lang.String alt) {
        return (Hello) super.setAlt(alt);
      }

      @Override
      public Hello setFields(java.lang.String fields) {
        return (Hello) super.setFields(fields);
      }

      @Override
      public Hello setKey(java.lang.String key) {
        return (Hello) super.setKey(key);
      }

      @Override
      public Hello setOauthToken(java.lang.String oauthToken) {
        return (Hello) super.setOauthToken(oauthToken);
      }

      @Override
      public Hello setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Hello) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Hello setQuotaUser(java.lang.String quotaUser) {
        return (Hello) super.setQuotaUser(quotaUser);
      }

      @Override
      public Hello setUserIp(java.lang.String userIp) {
        return (Hello) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.String who;

      /**

       */
      public java.lang.String getWho() {
        return who;
      }

      public Hello setWho(java.lang.String who) {
        this.who = who;
        return this;
      }

      @Override
      public Hello set(String parameterName, Object value) {
        return (Hello) super.set(parameterName, value);
      }
    }

  }

  /**
   * Builder for {@link Greetings}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Greetings}. */
    @Override
    public Greetings build() {
      return new Greetings(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link GreetingsRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setGreetingsRequestInitializer(
        GreetingsRequestInitializer greetingsRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(greetingsRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
